spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: manager-app-nip-io
            client-secret: H6EGA7EBc1ve0KMIt4rIgUnZdO5CCNEb
          metrics:
            client-id: manager-app-nip-io
            client-secret: H6EGA7EBc1ve0KMIt4rIgUnZdO5CCNEb
          discovery:
            client-id: manager-app-nip-io
            client-secret: H6EGA7EBc1ve0KMIt4rIgUnZdO5CCNEb