#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak.selm.ag.192.168.49.2.nip.io/realms/selmag
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.selm.ag.192.168.49.2.nip.io/realms/selmag